[env]
OUTPUT_CSS = { script = ["echo $(pwd)/public/app.css"] }

[tasks.run]
install_crate = { crate_name = "microserver", binary = "microserver", test_arg = ["--version"] }
dependencies = [ "build" ]
command = "microserver"
args = [
    "-p",
    "3000",
    "./public"
]

[tasks.build]
dependencies = [ "wasm-pack" ]
command = "cp"
args = [
    "index.html",
    "public/"
]

[tasks.clean]
dependencies = [ "cargo-clean", "static-clean" ]

[tasks.cargo-clean]
private = true
command = "cargo"
args = [ "clean" ]

[tasks.static-clean]
private = true
command = "rm"
args = [ "-rf", "public" ]

[tasks.wasm-pack]
private = true
dependencies = [ "create-public-dir" ]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = ["--version"] }
command = "wasm-pack"
args = [
    "build",
    "--no-typescript",
    "--dev",
    "--target",
    "no-modules",
    "--out-dir",
    "public"
]

[tasks.create-public-dir]
private = true
command = "mkdir"
args = ["public"]
